#!/bin/sh

HERE=`dirname $0`
OUTPUT_DIR=`readlink -f $HERE/out`
SRC_ROOT=`readlink -f $HERE/../src`
INC_ROOT=`readlink -f $HERE/../include`

if [ ! -d "$OUTPUT_DIR" ]; then
	mkdir "$OUTPUT_DIR"
fi

BOOST_LOC=`strings -n5 /etc/ld.so.cache | grep -E "\/.+libboost_program_options\.so" -m 1`
LD_ADD_DIR=`dirname $BOOST_LOC`

G_O_ARGS="-g -Os -std=c++11 -frtti -fexceptions -I$INC_ROOT -I$SRC_ROOT -pthread"
G_L_ARGS="-L$BOOST_LOC -lboost_program_options -lfreetype -pthread"

compile_files='bmfinfo bmfwriter'
cd $SRC_ROOT/bmf

for f in $compile_files
do
	g++ $G_O_ARGS $f.cpp -o $OUTPUT_DIR/$f $G_L_ARGS
done

cd $HERE